name: Build SukiSU-Ultra
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          timeout-minutes: 20

      - name: Apply SukiSU-Ultra non-gki patch
        run: |
          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s non-gki

      - name: Setup Android Kernel Build Env
        run: |
          sudo apt update
          sudo apt install -y build-essential libssl-dev bison flex bc python3

      - name: Build kernel
        run: |
          cp config .config
          make -j$(nproc)

      - name: Upload boot.img artifact
        uses: actions/upload-artifact@v4
        with:
          name: boot-img
          path: arch/arm64/boot/boot.img
