name: Build SukiSU-Ultra
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Apply SukiSU-Ultra patch (non-gki / non-gki for vili)
        run: |
          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s non-gki

      - name: Upload your kernel config
        uses: actions/upload-artifact@v4
        with:
          name: kernel-config
          path: config
